#!/usr/bin/env python3
"""Generate the two shipped lockups from the master mark.

    python3 docs/brand/lockups.py

`logo-dark.svg` and `logo-light.svg` are the theme-aware pair the README and the
docs use. They used to be hand-authored, which was fine while the mark was a
single stroked line and the wordmark was five letters. It stopped being fine when
the mark became a bell with a masked cutout and the word became nine letters: the
canvas had to grow, and a hand-set canvas that no longer fits its own contents
clips silently.

So the width is measured rather than chosen. The lockup is emitted once at a
generous width, the rendered ink is trimmed to find its true right edge, and the
file is rewritten at that edge plus a margin matching the left one. The mark
itself is read out of `nightbell-mark.svg`, so there is exactly one copy of the
geometry in this directory and the lockups cannot drift from the app.

Needs rsvg-convert and ImageMagick, the same two tools the rest of this directory
already assumes.
"""

import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
MASTER = os.path.join(HERE, "nightbell-mark.svg")

# Neither lockup paints a ground. They are composited onto whatever is behind
# them — the README's blue-glow plate, a docs page, a slide — and a baked-in ink
# rectangle showed up as a hard box sitting on that gradient. The dark/light pair
# differ only in the wordmark colour, which is the only thing that has to change.
WORD_ON_INK, WORD_ON_PAPER = "#FFFFFF", "#0B0E13"
FONT = "DejaVu Sans, Arial, sans-serif"

CANVAS_H = 190
MARK_H = 138          # the mark's ink height inside that canvas
MARK_X = 56           # left margin, and the right margin is matched to it
GAP = 54              # between mark and word
FONT_SIZE = 110
BASELINE = 126
TRACKING = -2


def master_fragment():
    """Everything inside the master mark's svg element, minus its comment."""
    src = open(MASTER).read()
    body = re.search(r"<svg[^>]*>(.*)</svg>", src, re.S).group(1)
    return body.strip()


def ink_box(fragment, px=512):
    """Ink bounds of a 512-space fragment, in 512 units."""
    probe = os.path.join(HERE, ".probe.svg")
    png = os.path.join(HERE, ".probe.png")
    open(probe, "w").write(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"'
        f' width="{px}" height="{px}">{fragment}</svg>\n'
    )
    subprocess.run(["rsvg-convert", "-w", str(px), probe, "-o", png], check=True)
    out = subprocess.run(
        ["magick", png, "-bordercolor", "none", "-border", "1", "-trim",
         "-format", "%w %h %X %Y", "info:"],
        capture_output=True, text=True, check=True,
    ).stdout
    w, h, x, y = (int(v) for v in re.findall(r"[-+]?\d+", out))
    for f in (probe, png):
        os.remove(f)
    k = 512 / px
    return x * k, y * k, w * k, h * k


def lockup(fragment, box, word_colour, width):
    bx, by, bw, bh = box
    s = MARK_H / bh
    tx = MARK_X - bx * s
    ty = CANVAS_H / 2 - (by + bh / 2) * s
    text_x = round(MARK_X + bw * s + GAP)
    return (
        "<!--\n"
        "  Generated by docs/brand/lockups.py — edit that, not this.\n"
        "  The mark is read from nightbell-mark.svg; the canvas width is measured\n"
        "  from the rendered ink so a longer word cannot clip.\n"
        "-->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{CANVAS_H}"'
        f' viewBox="0 0 {width} {CANVAS_H}" role="img" aria-label="Nightbell">\n'
        f'  <g transform="translate({tx:.2f} {ty:.2f}) scale({s:.4f})">\n'
        f"    {fragment}\n"
        "  </g>\n"
        f'  <text x="{text_x}" y="{BASELINE}" font-family="{FONT}" font-weight="bold"'
        f' font-size="{FONT_SIZE}" letter-spacing="{TRACKING}" fill="{word_colour}">'
        "Nightbell</text>\n"
        "</svg>\n"
    )


def right_edge(path):
    """Right edge of the rendered ink.

    Trimmed against transparency rather than against a colour. Flattening onto a
    ground first measured the dark lockup fine and silently mangled the light one:
    its wordmark is ink, the same value as any sensible dark ground, so the text
    trimmed away with the background and the canvas came out a third of its width.
    Transparency is the only ground both variants contrast with.
    """
    png = os.path.join(HERE, ".lock.png")
    subprocess.run(["rsvg-convert", "-w", "1400", path, "-o", png], check=True)
    out = subprocess.run(
        ["magick", png, "-bordercolor", "none", "-border", "1", "-trim",
         "-format", "%w %X", "info:"],
        capture_output=True, text=True, check=True,
    ).stdout
    w, x = (int(v) for v in re.findall(r"[-+]?\d+", out))
    src_w = int(re.search(r'width="(\d+)"', open(path).read()).group(1))
    os.remove(png)
    return (w + x) * src_w / 1400


def main():
    fragment = master_fragment()
    box = ink_box(fragment)
    for name, word in (("logo-dark.svg", WORD_ON_INK),
                       ("logo-light.svg", WORD_ON_PAPER)):
        path = os.path.join(HERE, name)
        open(path, "w").write(lockup(fragment, box, word, 1400))
        width = int(round(right_edge(path) + MARK_X))
        open(path, "w").write(lockup(fragment, box, word, width))
        print(f"wrote {name} at {width} x {CANVAS_H}")


if __name__ == "__main__":
    main()
