"""The browser favicon, generated from the same geometry as the Android assets.

Run after changing any geometry in android_assets.py:

    python3 docs/brand/web_favicon.py

It writes website/public/favicon.svg and website/public/favicon.ico. Both are
committed, because the website build does not run Python and a deploy must not
depend on rsvg-convert being installed on the machine doing it.

Three things differ from every Android canvas, and all three are because a
browser tab is not a launcher:

The plate is gone. On Android the mark sits on an opaque #0B0E13 rounded rect
because a launcher icon owns its whole tile. A tab strip does not: it is light in
a light theme and dark in a dark one, and a dark plate in a light tab reads as a
smudge, while in a dark tab it disappears into the chrome and leaves the inset
mark looking like a speck of dust. So the background is transparent and the bell
carries the brand blue on its own, which is what the mask cutout was built to
allow. The trace is a real hole, so whatever the browser paints behind the tab
shows through it, dark on a dark tab and white on a light one.

`fill` is 1.0, not the fraction the launcher canvases use. Adaptive icons reserve
a safe zone because the system crops them. Nothing crops a favicon, so the ink
runs edge to edge and every pixel goes to the mark. The mark is taller than it is
wide (244 x 303 in the 512 space), so height is what touches the edges, and the
9.7% left and right is the mark's own aspect ratio rather than padding that was
added. Removing that too would mean scaling the axes differently, which is not
padding, it is a different bell.

The trace is stroked inside the mask rather than buffered into an outline
polygon. android_assets.py needs shapely for that because a VectorDrawable
cannot stroke inside a mask. SVG can, so it does, and the two agree because the
stroke width is the same number scaled the same way.

## Why 16 is not just 32 rendered smaller

At `fill` 1.0 the trace stroke is 31.94 units in the 512 space, which is 2.00px
at 32 and 1.00px at 16. One pixel is the thinnest line a raster can hold, so
after antialiasing the 16px trace arrives as a broken grey smear and the mark
reads as a plain bell. The ICO container holds an independent image per size, so
the 16px entry is rendered from a variant whose stroke is boosted 1.6x and the
larger entries are not. This is a hinting decision at one size, not a change to
the mark: nothing outside the 16px entry of favicon.ico sees BOOST_16.
"""

import os
import struct
import subprocess
import tempfile

from android_assets import (
    BLUE,
    CLAPPER,
    CROWN,
    TRACE,
    TRACE_STROKE,
    bell_path,
    circle_path,
    fitter,
)

HERE = os.path.dirname(os.path.abspath(__file__))
PUBLIC = os.path.normpath(os.path.join(HERE, "..", "..", "website", "public"))

CANVAS = 512

# The sizes that go into the .ico, each mapped to the stroke boost it is rendered
# with. 16 and 32 are what a tab strip and a bookmark bar ask for; 48 is the size
# Google's crawler prefers for the favicon beside a search result, and the
# largest worth carrying before favicon.svg takes over for anything bigger.
ICO = {16: 1.6, 32: 1.0, 48: 1.0}


def svg(boost=1.0):
    """The mark as SVG. `boost` widens only the trace, for small-size hinting."""
    pt, s = fitter(CANVAS, 1.0)
    stroke = TRACE_STROKE * s * boost
    trace = "M" + "L".join(f"{x:.2f},{y:.2f}" for x, y in (pt(x, y) for x, y in TRACE))
    note = (
        ""
        if boost == 1.0
        else f"\n  Trace stroke boosted {boost}x for small-size legibility.\n"
    )
    return f"""<!--
  Generated by docs/brand/web_favicon.py. Do not edit by hand.

  The Nightbell mark: the heartbeat trace knocked out of a bell, brand blue on a
  transparent ground so it reads in a light tab and a dark one. The trace is the
  same six points the Pulse mark drew, so the old identity survives inside the
  new one.
{note}
  Geometry lives in docs/brand/android_assets.py. Change it there, then run this
  and android_assets.py both.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" \
width="{CANVAS}" height="{CANVAS}" role="img" aria-label="Nightbell">
  <defs>
    <mask id="nb-cut" maskUnits="userSpaceOnUse" x="0" y="0" \
width="{CANVAS}" height="{CANVAS}">
      <path d="{bell_path(pt)}" fill="#fff"/>
      <path d="{circle_path(pt, s, CROWN)}" fill="#fff"/>
      <path d="{circle_path(pt, s, CLAPPER)}" fill="#fff"/>
      <path d="{trace}" fill="none" stroke="#000" stroke-width="{stroke:.2f}" \
stroke-linecap="round" stroke-linejoin="round"/>
    </mask>
  </defs>
  <rect width="{CANVAS}" height="{CANVAS}" fill="{BLUE}" mask="url(#nb-cut)"/>
</svg>
"""


def pack_ico(pngs):
    """An ICO whose frames are PNG payloads rather than raw BMP.

    ImageMagick's ICO writer stores uncompressed 32-bit BMP, so 16 + 32 + 48
    costs 4*(16^2 + 32^2 + 48^2) = 14 kB before headers. The container has
    allowed a PNG payload per frame since Windows Vista and every browser that
    reads an .ico at all reads that form, which brings the same three frames to
    roughly 2 kB. On a file fetched on every cold visit that is worth the thirty
    lines of struct packing, and it is exactly the trade the rest of this site
    makes by precompressing everything it serves.

    Layout: a 6-byte ICONDIR, then one 16-byte ICONDIRENTRY per frame, then the
    payloads. Width and height are single bytes where 0 means 256, which is why
    nothing here may exceed 256.
    """
    entries, payloads, offset = [], [], 6 + 16 * len(pngs)
    for size, path in pngs:
        assert 0 < size <= 256, size
        data = open(path, "rb").read()
        entries.append(
            struct.pack(
                "<BBBBHHII",
                size if size < 256 else 0,
                size if size < 256 else 0,
                0,  # palette count, 0 for a truecolour image
                0,  # reserved
                1,  # colour planes
                32,  # bits per pixel
                len(data),
                offset,
            )
        )
        payloads.append(data)
        offset += len(data)
    return struct.pack("<HHH", 0, 1, len(pngs)) + b"".join(entries) + b"".join(payloads)


def main():
    svg_path = os.path.join(PUBLIC, "favicon.svg")
    open(svg_path, "w").write(svg())
    print(f"wrote favicon.svg      {os.path.getsize(svg_path):>6} B")

    # rsvg-convert rather than magick for the rasters: magick's own SVG renderer
    # ignores the mask and fills the whole rect, which silently produces a solid
    # blue square. rsvg is librsvg, the same engine GTK uses, and honours it.
    ico_path = os.path.join(PUBLIC, "favicon.ico")
    with tempfile.TemporaryDirectory() as tmp:
        pngs = []
        for size, boost in sorted(ICO.items()):
            src = os.path.join(tmp, f"{size}.svg")
            png = os.path.join(tmp, f"{size}.png")
            open(src, "w").write(svg(boost))
            subprocess.run(
                ["rsvg-convert", "-w", str(size), "-h", str(size), src, "-o", png],
                check=True,
            )
            # Strip the ancillary chunks rsvg writes. They are a few hundred bytes
            # of timestamp and software name across three frames, and a timestamp
            # would make the .ico a different file on every run for no reason.
            subprocess.run(["magick", png, "-strip", png], check=True)
            pngs.append((size, png))
        open(ico_path, "wb").write(pack_ico(pngs))

    sizes = ", ".join(f"{n}@{b}x" for n, b in sorted(ICO.items()))
    print(f"wrote favicon.ico      {os.path.getsize(ico_path):>6} B   {sizes}")

    _, s = fitter(CANVAS, 1.0)
    for size, boost in sorted(ICO.items()):
        px = TRACE_STROKE * s * boost * size / CANVAS
        print(f"  trace at {size:>2}px      {px:.2f}px")


if __name__ == "__main__":
    main()
